### ISSUE TITLE
This Lab Manual needs an overhaul

### ISSUE THREAD

**Issue by nickshields** [yqh/ECE254#9]
Just reiterating how most students feel about the current lab manual.

**Comment by jzarnett** [comment]
Hi,

Thanks for your feedback. We welcome the opportunity to make improvements to the labs that make it easier for you as students to understand what is asked of you. 

What would help us to do that, though, is to be specific. Some examples might be:

* On page x, the second paragraph is confusing 
* In lab y, it would be helpful to include an explanation of abc 
* In lab z, the screenshot figure n is outdated. 

These kinds of things would then be actionable. So any specific concerns you have, please provide them. Without being specific, we don't know what parts are working well for you and which ones could be improved. 

Thanks.

**Comment by yqh** [comment]
‎Thank you very much for keeping an eye on the manual issue reported  Jeff!Your reply is excellent and very helpful. Irene                                                                                                                                                                                                                 From: Jeff ZarnettSent: Friday, October 13, 2017 07:06To: yqh/ECE254Reply To: yqh/ECE254Cc: SubscribedSubject: Re: [yqh/ECE254] This Lab Manual needs an overhaul (#9)Hi,
Thanks for your feedback. We welcome the opportunity to make improvements to the labs that make it easier for you as students to understand what is asked of you.
What would help us to do that, though, is to be specific. Some examples might be:

On page x, the second paragraph is confusing
In lab y, it would be helpful to include an explanation of abc
In lab z, the screenshot figure n is outdated.

These kinds of things would then be actionable. So any specific concerns you have, please provide them. Without being specific, we don't know what parts are working well for you and which ones could be improved.
Thanks.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/yqh/ECE254","title":"yqh/ECE254","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/yqh/ECE254"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jzarnett in #9: Hi,\r\n\r\nThanks for your feedback. We welcome the opportunity to make improvements to the labs that make it easier for you as students to understand what is asked of you. \r\n\r\nWhat would help us to do that, though, is to be specific. Some examples might be:\r\n\r\n* On page x, the second paragraph is confusing \r\n* In lab y, it would be helpful to include an explanation of abc \r\n* In lab z, the screenshot figure n is outdated. \r\n\r\nThese kinds of things would then be actionable. So any specific concerns you have, please provide them. Without being specific, we don't know what parts are working well for you and which ones could be improved. \r\n\r\nThanks. "}],"action":{"name":"View Issue","url":"https://github.com/yqh/ECE254/issues/9#issuecomment-336421862"}}}

**Comment by nickshields** [comment]
On page 42 of the lab manual, in the pre-lab section, it mentions:
_Read Section 3.2.2 about fork() and exec() and Sections 3.4.1 and 3.4.2 about wait() in [6]._

-It should be section 3.2.5 fork() and exec()
-On the bibliography page, the link for http://advancedlinuxprogramming.com/ doesn't return anything useful. 

I will update this issue if I find anything else. 

Thanks!

**Comment by jzarnett** [comment]
Thanks; we have noted this down and will make the changes in the future (it's a busy time right now so I can't promise I'll get it done immediately).

**Comment by jzarnett** [comment]
Course is retired.
